### ISSUE TITLE
Players in staff mode can interact with boats

### ISSUE THREAD

**Issue by teszeo** [UnicraftNetwork/Staff#2]
If im in mod mode i can destroy or join boats

![image](https://user-images.githubusercontent.com/55764934/90294666-982a2100-de4c-11ea-8ab8-46150192d85e.png)

**Comment by BGMP** [comment]
Has been fixed as of https://github.com/UnicraftNetwork/Staff/commit/322b6aa6c6f497cebc792a061b46692a14efbe67, commit which, in addition, prevents vanished players from entering beds
